config/routes.rb
Prueba2::Application.routes.draw do
  
    
  get "activities/index"

  get 'activities/notificaciones'

  
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

  match '/session' =>  "clearance/sessions#create"
  
  match '/sign_out' =>  "clearance/sessions#destroy"

  match '/sign_in' =>  "clearance/sessions#new"

  match '/sign_up' =>  "clearance/users#new"
  
  

   root :to => 'inicio#show'

  match "dashboard" => "dashboard#show"

   match "game" => "dashboard#game"
    

  
end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
attr_accessible :biography, :country, :email, :fullname , :user_id , :avatar


include PublicActivity::Model

validates :fullname, :presence =>true
validates :country,  :presence =>true
validates :email,  :presence =>true
validates :user_id, :uniqueness => true



mount_uploader :avatar, AvatarUploader

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

include PublicActivity::StoreController

before_filter :authorize , except: [:show]

def index

  @profiles = Profile.all

end

def new 

 @profile = Profile.new

end	

def create	

@user = current_user
@profile = Profile.new(params[:profile])	
@profile.wallet = 40000
@profile.user_id =current_user.id
@user.name = @profile.fullname

if @profile.save

@user.save
## poner en cero todo lo de user badge



redirect_to @profile
else

flash[:notice] = "You already have a profile"
      redirect_to dashboard_path 

end

		

end	

def show


@profile = Profile.find(params[:id])
     

end

def edit

  

  @profile = Profile.find_by_user_id(params[:id])
 
 end

  def update
     @profile = Profile.find(params[:id])
    if @profile.update_attributes(params[:profile])
      redirect_to @profile
    else
      render :new
    end
  end




def myprofile




  @profile = Profile.find_by_user_id(params[:id])

   if @profile == nil
   
     flash[:notice] = "You have no profile please create one"
     redirect_to new_profile_path(@profile) 
   
  # elsif @profile.user_id != current_user.id

   # flash[:notice] = "You only can access to ur profile!"
    #redirect_to dashboard_path

  end
  

     
 
  
end



def subida

render :uploadphoto
@profiles = Profile.find_by_user_id(params[:id])

end

def uploadphoto

@profiles = Profile.find_by_user_id(params[:id])



#@profile.avatar = params[:avatar]
#@profile.avatar = File.open('somewhere')



#@profile.save!
#@profile.avatar.url # => '/url/to/file.png'
#@profile.avatar.current_path # => 'path/to/file.png'
#@profile.avatar.identifier # => 'file.png'


redirect_to @profile

end

#metodo para mostrar perfil usando el user id

def user

  
  @profile = Profile.find_by_user_id(params[:id])


end






end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for @profile, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :fullname %><br>
  <%= f.input :email %><br>
  <%= f.input :country %><br>
  <%= f.input :biography %><br>
  

  
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                profiles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb


<p>
     <%= profile.fullname %>
</p><br>


 

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fullname) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:biography) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%= model_class.human_attribute_name(:wallet) %></th>
      <th><%= model_class.human_attribute_name(:money) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.id, profile_path(profile) %></td>
        <td><%= profile.fullname %></td>
        <td><%= profile.email %></td>
        <td><%= profile.country %></td>
        <td><%= profile.biography %></td>
        <td><%= profile.user_id %></td>
        <td><%= profile.avatar %></td>
        <td><%= profile.wallet %></td>
        <td><%= profile.money %></td>
        <td><%=l profile.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_profile_path(profile), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      profile_path(profile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_profile_path,
            :class => 'btn btn-primary' %>

app/views/profiles/myprofile.html.erb
<div class="row">
<div class="row-fluid">

<br><br>
<div class="span3">
	
<% if @profile.avatar? %>
<div id="image">
<%= image_tag @profile.avatar_url(:thumb).to_s  %>

</div>

<% else %>
<div id="image">
<%= image_tag "http://mashwork.com/blog/wp-content/uploads/2012/06/Unknown-person2.gif" %>
</div>
<% end %>
</div> <!-- fin del div 3 -->


<div class="span8">

<h4 class ="subheader"><%= @profile.fullname %> / <%= @profile.country %></h4>
<h5 class ="subheader"><br>Contact: <%= @profile.email %><br>

BIO :<%= @profile.biography %><br><br><br>


My wallet : <%= @profile.wallet %><br><br><br>

Where i Work (My startups) <br><br><br>


Where i Invest (My Investments)
</h5>




</div> <!-- fin de 8 culumns -->

<div class="span1">

<%= link_to "EDIT MY PROFILE" , edit_profile_path(current_user.id) %>

</div>


</div>
</div><br><br><br><br>

<center><%= link_to "Dashboard", dashboard_path %></center>


<br><br><br>

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/noprof.html.erb


<h1 class="subheader"> You have no profile  create one    <%= link_to " here ", new_profile_path(@profile) %> </h1>

app/views/profiles/show.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fullname) %>:</strong></dt>
  <dd><%= @profile.fullname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @profile.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @profile.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:biography) %>:</strong></dt>
  <dd><%= @profile.biography %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @profile.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= @profile.avatar %></dd>
  <dt><strong><%= model_class.human_attribute_name(:wallet) %>:</strong></dt>
  <dd><%= @profile.wallet %></dd>
  <dt><strong><%= model_class.human_attribute_name(:money) %>:</strong></dt>
  <dd><%= @profile.money %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              profiles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_profile_path(@profile), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              profile_path(@profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/profiles/uploadphoto.html.erb

<div class="row">

<h3> Upload profile Photo  </h3>

<%= form_for @profile do |f| %>
  <%= f.file_field :avatar %>

  <%= f.button :submit , :class => 'nice small radius blue button' %>

<% end %>





</div>

app/views/profiles/user.html.erb




<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fullname) %>:</strong></dt>
  <dd><%= @profile.fullname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @profile.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @profile.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:biography) %>:</strong></dt>
  <dd><%= @profile.biography %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @profile.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= @profile.avatar %></dd>
  <dt><strong><%= model_class.human_attribute_name(:wallet) %>:</strong></dt>
  <dd><%= @profile.wallet %></dd>
  <dt><strong><%= model_class.human_attribute_name(:money) %>:</strong></dt>
  <dd><%= @profile.money %></dd>
</dl>