config/routes.rb
Prueba2::Application.routes.draw do
  
    
  get "activities/index"

  get 'activities/notificaciones'

  
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

  match '/session' =>  "clearance/sessions#create"
  
  match '/sign_out' =>  "clearance/sessions#destroy"

  match '/sign_in' =>  "clearance/sessions#new"

  match '/sign_up' =>  "clearance/users#new"
  
  

   root :to => 'inicio#show'

  match "dashboard" => "dashboard#show"

   match "game" => "dashboard#game"
    

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "VcWings" %></title>
  

  
 

	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	

  
  <%= csrf_meta_tags %>
</head>
<body>
<br>
<header>



 <div  class="row-fluid">

  <div class="span1">
  </div>  

  <div class="span1">
     <%= link_to image_tag("http://res.cloudinary.com/bogdecom/image/upload/v1371438372/mini_u2q4bn.png" , :class =>"brand") , root_path %>
  </div>


  <div class="span3" >

  <div class="row-fluid">
   
      <div class="span6">
      <h5>PLAY <a href="dashboard/game">your invest</a></h5>
       </div>
  

       <div class="span6">
      <h5>UPLOAD <a href="#">your startup</a></h5>
        </div>


   </div>
  </div>



  <div class="span3">

    <div class="input-append">

      <%= form_tag ( {:controller => "dashboard" , :action => "search"} ) do %>
      <%= text_field_tag(:name)   %>
      
      <button class='btn btn-info' style='width:40px;'>
      <i class="icon-search"></i>
      </button>


      

      <% end %>


    </div>

  </div>
    

    <% if signed_in? %>

     <div class="span3">

      <h5><%= link_to "LOG OUT   ", sign_out_path, :method => :delete %></h5>
     </div>





    <% else %>
    <div class="span1">
    <h5><%= link_to "LOGIN", sign_in_path %></h5></div>  


   <div class="span1">
   <h5><%= link_to " JOIN   ", sign_up_path %> <span class="divider"></h5></div>  
 
    <div class="span1">

    <h5>ABOUT</h5>

    </div>  







     <% end %>    

     <div class="span1">
    </div>  


   </div>
   
</div>







</header>  







<header>
<center>
<br>
        <% if signed_in? %>
        <ul class="breadcrumb" >

              
              <li>&nbsp;<%= link_to "Dashboard ", dashboard_path %><span class="divider">/</span></li> 

              <li>&nbsp;&nbsp;<%= link_to "My Profile  ",  :controller => :profiles , :action => :myprofile , :id=>current_user.id %><span class="divider">/</span></li>

             
              <li>&nbsp;<%= link_to " My Startups ", :controller => :startups , :action => :mystartups , :id=> current_user.id %><span class="divider">/</span></li>
             

              <li>&nbsp;&nbsp;<%= link_to " Create Startup  ", new_startup_path(@startup)   %><span class="divider">/</span></li>
              
               <li>&nbsp;<%= link_to " My Investments  ", :controller => :investments , :action => :myinvestments , :id=> current_user.id   %><span class="divider">/</span></li>

              <li>&nbsp;<%= link_to "Sign out   ", sign_out_path, :method => :delete %> <span class="divider">/</span></li>
              
             
             
               
         
              
               





              <li> </li>




      </ul> <% end %>   
   
  




 






</center>
</header> <!-- fin del header -->




 



  
  <%= yield %>
 
  

<%= javascript_include_tag "application" %>
    

    <script>

$('.carousel').carousel({
  interval: 5000


})


</script>

</body>
</html>

app/views/layouts/inicio.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "VcWings" %></title>
  

  
 

	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	

  
  <%= csrf_meta_tags %>
</head>
<body>
<br>
<header>



 <div  class="row-fluid">

  <div class="span1">
  </div>  

  <div class="span1">
     <%= link_to image_tag("http://res.cloudinary.com/bogdecom/image/upload/v1371438372/mini_u2q4bn.png" , :class =>"brand") , root_path %>
  </div>


  <div class="span3" >

  <div class="row-fluid">
   
      <div class="span6">
      <h5>PLAY <a href="dashboard/game">your invest</a></h5>
       </div>
  

       <div class="span6">
      <h5>UPLOAD <a href="#">your startup</a></h5>
        </div>


   </div>
  </div>



  <div class="span3">

    <div class="input-append">

      <%= form_tag ( {:controller => "dashboard" , :action => "search"} ) do %>
      <%= text_field_tag(:name) %>
      
      <button class='btn btn-info' style='width:40px;'>
      <i class="icon-search"></i>
      </button>





      <% end %>
    </div>

  </div>
    

    <% if signed_in? %>

     <div class="span3">

      <h5><%= link_to "LOG OUT   ", sign_out_path, :method => :delete %></h5>
     </div>





    <% else %>
    <div class="span1">
    <h5><%= link_to "LOGIN", sign_in_path %></h5></div>  


   <div class="span1">
   <h5><%= link_to " JOIN   ", sign_up_path %> <span class="divider"></h5></div>  
 
    <div class="span1">

    <h5>ABOUT</h5>

    </div>  







     <% end %>    

     <div class="span1">
    </div>  


   </div>
   
</div>







</header>  


<!--
<div class="row-fluid">
<div class="hero-unit" style="margin:0;background-image:url('http://24.media.tumblr.com/768947d07cbaa17520503ce7a43bc0c5/tumblr_mpsdhy1guB1qm5n7fo1_1280.png');">
 


    <div class="span4"> <center>

      <h2>UPLOAD YOUR STARTUP</h2>  <BR><BR></center>
    </div>

    <div class="span3"> <center>

     <h2>GAIN TRACKING</h2><br><div id="div_show">
   
      <br>
    </h3></div> </center>

    </div>

    <div class="span5"> 
     <center>
    <h2>PITCH TO THE WORLD!</h2><BR><BR></center>

    </div>
<BR><BR><BR><BR><BR><BR>
</div>
</div>
</div>-->

<div style="text-align:center; width:100%; ">
<img id="Image-Maps_9201307111544261" src="http://24.media.tumblr.com/768947d07cbaa17520503ce7a43bc0c5/tumblr_mpsdhy1guB1qm5n7fo1_1280.png" usemap="#Image-Maps_9201307111544261" border="0" width="100%" height="308" alt="" />
<map id="_Image-Maps_9201307111544261" name="Image-Maps_9201307111544261">
<area shape="rect" coords="532,194,719,235" href="http://vimeo.com/39679411" alt="" title=""    />
<area shape="rect" coords="1278,306,1280,308" href="http://www.image-maps.com/index.php?aff=mapped_users_9201307111544261" alt="Image Map" title="Image Map" />
</map>
<!-- Image map text links - Start - If you do not wish to have text links under your image map, you can move or delete this DIV -->


</div>
        





  <%= yield %>






 <%= javascript_include_tag "application" %>
    

    <script>

$('.carousel').carousel({
  interval: 5000


})


</script>

</body>
</html>










