config/routes.rb
Prueba2::Application.routes.draw do
  
    
  get "activities/index"

  get 'activities/notificaciones'

  
  resources :activities
  resources :profiles 
  
  resources :startups do
  
   
     collection do
      get :random
    end

    resources :investments
    resources :activities    
    resources :members do
 
       get :autocomplete_profiles_name, :on => :collection
    end
 
    resources :comments
  end

 

  match ':controller(/:action(/:id))(.:format)'

  match '/session' =>  "clearance/sessions#create"
  
  match '/sign_out' =>  "clearance/sessions#destroy"

  match '/sign_in' =>  "clearance/sessions#new"

  match '/sign_up' =>  "clearance/users#new"
  
  

   root :to => 'inicio#show'

  match "dashboard" => "dashboard#show"

   match "game" => "dashboard#game"
    

  
end

app/models/member.rb
class Member < ActiveRecord::Base
  

  belongs_to :profile
  belongs_to :startup
  belongs_to :user
  
  attr_accessible :job, :mtype , :user_id ,:startup_id ,:email ,:name
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json

  before_filter :authorize , except: [:show]

  autocomplete :profiles, :column_name => 'fullname',  :full => true 
  
  def index

    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end

  end

  def show 

    #@member =Member.find(params[:id])

    @member = Member.new
   

  end

  def _member
   
   @member = Member.new


  end

  def new 
  
  
 @members = Member.new
 @startups= Startup.find(params[:startup_id])
 
 end


 def create

  @startups= Startup.find(params[:startup_id])

  @member = Member.new(params[:member])

  @profile = Profile.find_by_email(@member.email)

  @member.startup_id = @startups.id

  @member.user_id = @profile.user_id

  @member.profile_id = @profile.id

  @member.name = @profile.fullname

  if @member.save

  redirect_to @startups

  else

  render "new"
  
  end 

 end


 


 def edit

  @members = Member.find(params[:id])
  @startups =Startup.find(@members.startup_id)


 end 


 def update


   @members = Member.find(params[:id])
   @startups =Startup.find(@members.startup_id)

    if @members.update_attributes(params[:members])
      redirect_to @startups
    else
      render :edit
    end


 end

def destroy

     
@member = Member.find(params[:id])    
@member.destroy
redirect_to "/startups/mystartups/#{current_user.id}"
end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<div class= "row">

<%= simple_form_for([@startups, @startups.members.build]) do |f| %>
 

<%= f.input :name, :url =>autocomplete_profiles_name_startup_members_path, :as=>:autocomplete %>




<%= f.input :email   %>


 <%= f.input :job %>


 <%= f.input :mtype , :label =>'Member type' , :placeholder => 'Cofounder / Member' %>
 
 <%= f.button :submit, :class => 'nice small radius blue button'  %>
 
 <% end %>
</div>

app/views/members/_member.html.erb

<!-- este es el que muestra los members en show -->


<p>
      <%= link_to member.name  , :controller => :profiles , :action => :show , :id=> member.profile_id  %> &nbsp;&nbsp;&nbsp;&nbsp; <%= member.job %> / <%= member.mtype %>

</p><br>


 

 

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Job</th>
    <th>Member type</th>
    <th>Startup id</th>
    <th>Profile id</th>
    <th>Email</th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.job %></td>
    <td><%= member.mtype %></td>
    <td><%= member.startup_id %></td>
     <td><%= member.profile_id %></td>
     <td><%= member.email %></td>

     <td>
     <%= link_to "edit" , edit_startup_member_path(member.startup_id ,member)%>

     <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      startup_member_path(member.startup_id ,member),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>


   </td>

  </tr>
<% end %>
</table>

<br />

app/views/members/new.html.erb
 <h2 class="subheader">New Member </h2>
 <%= render :partial => 'form' %>